[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "yalab_procedures"
version = "0.0.1"
description = "The yalab-procedures repository is dedicated to managing and executing data processing procedures for MRI data in the Assaf Neuro Lab. This project aims to standardize and automate the various steps involved in processing structural and diffusion MRI data, ensuring consistency, efficiency, and traceability in our research workflows."
readme = "README.rst"
authors = [
  {name = "YALab DevOps", email = "yalab.dev@gmail.com"}
]
maintainers = [
  {name = "YALab DevOps", email = "yalab.dev@gmail.com"}
]
classifiers = [

]
license = {text = "MIT license"}
dependencies = [
  "typer"
]

[project.optional-dependencies]
dev = [
    "coverage",  # testing
    "mypy",  # linting
    "pytest",  # testing
    "ruff"  # linting
]

[project.urls]

bugs = "https://github.com/yalab-dev/yalab_procedures/issues"
changelog = "https://github.com/yalab-dev/yalab_procedures/blob/master/changelog.md"
homepage = "https://github.com/yalab-dev/yalab_procedures"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"*" = ["*.*"]




# Mypy
# ----

[tool.mypy]
files = "."

# Use strict defaults
strict = true
warn_unreachable = true
warn_no_return = true

[[tool.mypy.overrides]]
# Don't require test functions to include types
module = "tests.*"
allow_untyped_defs = true
disable_error_code = "attr-defined"

