name: Codecov Report

on: [push, pull_request]

jobs:
  build:
    name: Run tests and upload coverage to Codecov
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov  # Install pytest and pytest-cov to generate coverage reports
        pip install .  # Install your package

    - name: Run tests and collect coverage
      run: |
        pytest --cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.2.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Ensure your CODECOV_TOKEN is set in GitHub Secrets
        name: codecov-umbrella  # Optional: Name for the upload to distinguish it in the UI
