name: Codecov Report

on: [push, pull_request]

jobs:
  build:
    name: Run tests and upload coverage to Codecov
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install .  # Install your package

    - name: Verify directory structure
      run: |
        ls -R

    - name: Run tests and collect coverage
      run: |
        mkdir -p reports
        pytest --cov-report xml:reports/coverage.xml --cov=. tests/ --verbose

    - name: Check coverage file
      run: |
        cat reports/coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.2.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: reports/coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: true
